---
- hosts: all
  become: no  # Set to yes if necessary
  gather_facts: no
  tasks:
    - name: Change max_connections value in config file
      ansible.builtin.lineinfile:
        path: /home/ansadmin/config.cfg
        regexp: '^max_connections='
        line: 'max_connections=200'
