---
- hosts: all
  become: no
  gather_facts: no
  tasks:
    - name: Insert a line after a specific pattern
      lineinfile:
        path: /home/ansadmin/demo.txt
        line: "PortForwarding no"
        insertafter: "^some line after which new line will be added"